---
platform: linux
image_resource:
  type: docker-image
  source: {repository: bosh/integration}

inputs:
  - name: environment
  - name: bosh-cpi-src
  - name: stemcell-state
  - name: stemcell

run:
  path: bosh-cpi-src/ci/tasks/run-integration.sh

params:
  AZURE_ENVIRONMENT:                              ""
  AZURE_TENANT_ID:                                ""
  AZURE_SUBSCRIPTION_ID:                          ""
  AZURE_CLIENT_ID:                                ""
  AZURE_CLIENT_SECRET:                            ""
  AZURE_CERTIFICATE:                              ""
  SSH_PUBLIC_KEY:                                 ""
