#!/bin/bash

set -ex

cpi_dir=$(cd $(dirname $0)/../ && pwd)
cpi_gems_dir=$cpi_dir/src/bosh_azure_cpi

cleanup() {
  cd $cpi_gems_dir
  rm -f *.gem Gemfile*
}

trap cleanup EXIT

(
  cd $cpi_gems_dir

  rm -f *.gem

  cat > Gemfile <<EOF
source "https://rubygems.org"
gem "bosh_azure_cpi", github: "AbelHu/bosh_azure_cpi"
EOF

  bundle package --all
)
